apiVersion: v1
appVersion: 1.0.0
version: 1.0.0
name: wordpress-db
description: In class activity 3
keywords:
  - nginx
  - wordpress
  - mariadb
maintainers:
  - name: Yolimar Rios
    email: yolimar.rios23@gmail.com