apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.db.name }}-service
  labels:
  {{- toYaml .Values.db.labels | nindent 4 }}
spec:
  type: {{ .Values.db.service.type }}
  ports:
    - port: {{ .Values.db.service.port }}
      protocol: TCP
      targetPort: {{ .Values.db.service.targetPort }}
  selector:
  {{- toYaml .Values.db.labels | nindent 4 }}