apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nginx.name }}-service
  labels:
  {{- toYaml .Values.nginx.labels | nindent 4 }}
spec:
  type: {{ .Values.nginx.service.type }}
  ports:
    - port: {{ .Values.nginx.service.port }}
      protocol: TCP
      targetPort: {{ .Values.nginx.service.targetPort }}
  selector:
  {{- toYaml .Values.nginx.labels | nindent 4 }}