---
# Source: wordpress-app/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wp-wordpress-deployment
  labels:
    app: wp-wordpress-app
    env: dev
    id: c0904675
spec:
  selector:
    matchLabels:
      app: wp-wordpress-app
      env: dev
      id: c0904675
  replicas: 3
  template:
    metadata:
      labels:
        app: wp-wordpress-app
        env: dev
        id: c0904675
    spec:
      containers:
        - name: wp-wordpress
          image: wordpress:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: wp-wordpress-configmap
                optional: false
            - secretRef:
                name: wp-wordpress-secret
                optional: false
          ports:
            - containerPort: 80
