---
# Source: wordpress-db/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wp-database-deployment
  labels:
    app: wp-database-app
    env: dev
    id: c0904675
spec:
  selector:
    matchLabels:
      app: wp-database-app
      env: dev
      id: c0904675
  replicas: 1
  template:
    metadata:
      labels:
        app: wp-database-app
        env: dev
        id: c0904675
    spec:
      containers:
        - name: wp-database
          image: mariadb:10.6.4-focal
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: wp-database-configmap
                optional: false
            - secretRef:
                name: wp-database-secret
                optional: false
          ports:
            - containerPort: 3306
